---
- name: Install Apache
  ansible.builtin.package:
    name: apache2
    state: present

- name: Deploy index.html with system info
  ansible.builtin.template:
    src: index.html.j2
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: '0644'
  notify: Restart Apache

- name: Ensure Apache is running and enabled
  ansible.builtin.service:
    name: apache2
    state: started
    enabled: true

- name: Allow HTTP traffic on port 80
  ansible.builtin.ufw:
    rule: allow
    port: '80'
    proto: tcp
  when: ansible_facts['os_family'] == 'Debian'

- name: Check HTTP response from Apache
  ansible.builtin.uri:
    url: http://{{ ansible_host }}
    status_code: 200
...